# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4ca032f543a4b4cc8f87b3786759003bf44355e891b7b8723d76b1cf265d3e3450008076e04ea14e298ab9d9ce7a0b4b15d09355abec730f0182a3cfba99707

test:
  secret_key_base: 23ee3f3110b9d44bdfcb36f5ad310649ae47efc7abc6b9f2b9a106f21f5aecf534cc9be703aff5188b16414ba25a3e95c88cb5fa6ad49a9eae453a3d5af65923

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
